In [1]:
import tensorflow as ts

ModuleNotFoundError: No module named 'tensorflow'

import tensorflow as ts

In [3]:
!pip install numpy

In [4]:
import c:\users\user\appdata\local\programs\python\python39\lib\site-packages\numpy as np

ModuleNotFoundError: No module named 'numpy'

In [1]:
!pip install plotly


You should consider upgrading via the 'c:\users\user\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [2]:
!pip install sympy


You should consider upgrading via the 'c:\users\user\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [3]:
!pip install scipy


You should consider upgrading via the 'c:\users\user\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [4]:
!pip install pandas

You should consider upgrading via the 'c:\users\user\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [5]:
!pip install plotly_express

You should consider upgrading via the 'c:\users\user\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [6]:
from numpy import linalg as LA
from sympy import Matrix
from scipy.linalg import lu, qr
import plotly.express as px
import plotly.graph_objs as go
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
import math
import sys



# sys.path.insert(1, 'D:\AAlearnAA\Study\python')

from rutaul import pg,pm,pr,py
from packages import nets_draws as nd



........... 🆂  🆃  🅰   🆁  🆃 ...........


# The main method 

In [9]:


def generate_fig(matrix=np.array([[2,1, 0], [0,0,0], [0,0,1]])):


    fig = go.Figure()
    fig.update_layout(template='plotly_dark')
    draw = nd.Draw(fig=fig)
    draw.MainAxices()

    draw.determanent(nd.determanentParallelepiped(
        np.identity(3)), color='grey', name='unit Det')



    # Creating an object from class 
    draw.Mat3grid(nd.net3d(matrix), color='limegreen',
                    name='Col Base', opacity=0.9, width=2, showlegend=True)

    # draw.Mat3grid(nd.net3d(matrix.T), color='magenta', colorY='', colorZ='', name='Row Base', opacity=.6, width=2, showlegend=True)


    draw.Mat3grid(nd.net3d(np.identity(3)), color='grey', colorY='',
                colorZ='', name='Unit Base', opacity=.6, width=4, showlegend=True)


    # ##########################################################
    draw.determanent(nd.determanentParallelepiped(matrix), name='Col Det')

    # ##########################################################
    draw.MatVector(nd.matrixvector(matrix.T), namex='Row Vector')
    draw.determanent(nd.determanentParallelepiped(
        matrix.T), color='green', name='Row Det')

    # ##########################################################

    ns = nd.nullSpace(matrix, strt=-6, stp=6, num=2)
    draw.Nullspace(**ns)

    # ##########################################################

    val, mat, w, v = nd.eigenvector(matrix)
    print(v)
    draw.EigVector((val, mat))
    draw.determanent(nd.determanentParallelepiped(v), name='eigen Determent',color='deepskyblue')

    mem = v.T
    draw.MatVector(nd.matrixvector(mem), namex='TTeigenTT Vector')
    draw.determanent(nd.determanentParallelepiped(
        mem), name='TTeigenTT Determent', color='purple')

    # ##########################################################
    # ###################    Inverses    #######################
    # ##########################################################
    c, r = matrix.shape
    # checking if the matrix is invertible
    if np.linalg.matrix_rank(matrix) == c and c == r:
        inverse = np.linalg.inv(matrix)
        draw.MatVector(nd.matrixvector(inverse), namex='col inv Vec')
        draw.determanent(nd.determanentParallelepiped(
            inverse), color='red', name='Col inv Det')

        #    ##########################################################

        inverseRow = np.linalg.inv(matrix.T)
        draw.MatVector(nd.matrixvector(inverseRow), namex='Row Inv Vector')
        draw.determanent(nd.determanentParallelepiped(
            inverseRow), color='pink', name='Row inv Det')


    vtest = np.array([[-0.4472136],[ 0.8944272],[0]])

    print(matrix.dot(vtest))
    print(matrix.dot(2*vtest))
    return fig


mat = np.array([[2,1, 0], [0,1,0], [0,0,1]])
fig = generate_fig(mat)
fig.show()

vector
[[-1.3  1.3]
 [-1.  -1. ]
 [-1.  -1. ]]
matrix
[[2 1 0]
 [0 1 0]
 [0 0 1]]
dot priduct
[[-3.6  1.6]
 [-1.  -1. ]
 [-1.  -1. ]]
vector
[[-1.3  1.3]
 [ 0.   0. ]
 [-1.  -1. ]]
matrix
[[2 1 0]
 [0 1 0]
 [0 0 1]]
dot priduct
[[-2.6  2.6]
 [ 0.   0. ]
 [-1.  -1. ]]
vector
[[-1.3  1.3]
 [ 1.   1. ]
 [-1.  -1. ]]
matrix
[[2 1 0]
 [0 1 0]
 [0 0 1]]
dot priduct
[[-1.6  3.6]
 [ 1.   1. ]
 [-1.  -1. ]]
vector
[[-1.3  1.3]
 [-1.  -1. ]
 [ 0.   0. ]]
matrix
[[2 1 0]
 [0 1 0]
 [0 0 1]]
dot priduct
[[-3.6  1.6]
 [-1.  -1. ]
 [ 0.   0. ]]
vector
[[-1.3  1.3]
 [ 0.   0. ]
 [ 0.   0. ]]
matrix
[[2 1 0]
 [0 1 0]
 [0 0 1]]
dot priduct
[[-2.6  2.6]
 [ 0.   0. ]
 [ 0.   0. ]]
vector
[[-1.3  1.3]
 [ 1.   1. ]
 [ 0.   0. ]]
matrix
[[2 1 0]
 [0 1 0]
 [0 0 1]]
dot priduct
[[-1.6  3.6]
 [ 1.   1. ]
 [ 0.   0. ]]
vector
[[-1.3  1.3]
 [-1.  -1. ]
 [ 1.   1. ]]
matrix
[[2 1 0]
 [0 1 0]
 [0 0 1]]
dot priduct
[[-3.6  1.6]
 [-1.  -1. ]
 [ 1.   1. ]]
vector
[[-1.3  1.3]
 [ 0.   0. ]
 [ 1.   1. ]]
matrix
[[2 1 0]

# Let us try different matrices

# Let us stretch the space

In [ ]:
mat = np.array([[2,-1, 0], [-1,2,0], [0,0,0]])
fig = generate_fig(mat)
fig.show()

# Let us sheer the space

In [ ]:
sqr = np.sqrt(2)
mat = np.array([[  1  ,  1  , 0  ], [  2   ,  1  ,0], [0,0,2]])
fig = generate_fig(mat)
fig.show()

In [ ]:
sqr = np.sqrt(2)
mat = np.array([[  1  ,  2  , 1  ], [  1   ,  2   ,1], [0,0,0]])
fig = generate_fig(mat)
fig.show()